package com.project.model;
// Generated Apr 11, 2017 7:41:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * EventtrackstableId generated by hbm2java
 */
public class EventtrackstableId implements java.io.Serializable {

	private BigDecimal eventid;
	private String eventtracks;

	public EventtrackstableId() {
	}

	public EventtrackstableId(BigDecimal eventid, String eventtracks) {
		this.eventid = eventid;
		this.eventtracks = eventtracks;
	}

	public BigDecimal getEventid() {
		return this.eventid;
	}

	public void setEventid(BigDecimal eventid) {
		this.eventid = eventid;
	}

	public String getEventtracks() {
		return this.eventtracks;
	}

	public void setEventtracks(String eventtracks) {
		this.eventtracks = eventtracks;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtrackstableId))
			return false;
		EventtrackstableId castOther = (EventtrackstableId) other;

		return ((this.getEventid() == castOther.getEventid()) || (this.getEventid() != null
				&& castOther.getEventid() != null && this.getEventid().equals(castOther.getEventid())))
				&& ((this.getEventtracks() == castOther.getEventtracks())
						|| (this.getEventtracks() != null && castOther.getEventtracks() != null
								&& this.getEventtracks().equals(castOther.getEventtracks())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventid() == null ? 0 : this.getEventid().hashCode());
		result = 37 * result + (getEventtracks() == null ? 0 : this.getEventtracks().hashCode());
		return result;
	}

}
