package com.project.model;
// Generated Apr 11, 2017 7:41:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * EventtypeId generated by hbm2java
 */
public class EventtypeId implements java.io.Serializable {

	private BigDecimal eventid;
	private BigDecimal eventtypeid;

	public EventtypeId() {
	}

	public EventtypeId(BigDecimal eventid, BigDecimal eventtypeid) {
		this.eventid = eventid;
		this.eventtypeid = eventtypeid;
	}

	public BigDecimal getEventid() {
		return this.eventid;
	}

	public void setEventid(BigDecimal eventid) {
		this.eventid = eventid;
	}

	public BigDecimal getEventtypeid() {
		return this.eventtypeid;
	}

	public void setEventtypeid(BigDecimal eventtypeid) {
		this.eventtypeid = eventtypeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtypeId))
			return false;
		EventtypeId castOther = (EventtypeId) other;

		return ((this.getEventid() == castOther.getEventid()) || (this.getEventid() != null
				&& castOther.getEventid() != null && this.getEventid().equals(castOther.getEventid())))
				&& ((this.getEventtypeid() == castOther.getEventtypeid())
						|| (this.getEventtypeid() != null && castOther.getEventtypeid() != null
								&& this.getEventtypeid().equals(castOther.getEventtypeid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventid() == null ? 0 : this.getEventid().hashCode());
		result = 37 * result + (getEventtypeid() == null ? 0 : this.getEventtypeid().hashCode());
		return result;
	}

}
