package com.project.model;
// Generated Apr 11, 2017 7:41:13 PM by Hibernate Tools 4.3.5.Final

/**
 * Eventtrackstable generated by hbm2java
 */
public class Eventtrackstable implements java.io.Serializable {

	private EventtrackstableId id;

	public Eventtrackstable() {
	}

	public Eventtrackstable(EventtrackstableId id) {
		this.id = id;
	}

	public EventtrackstableId getId() {
		return this.id;
	}

	public void setId(EventtrackstableId id) {
		this.id = id;
	}

}
