package com.project.model;
// Generated Apr 11, 2017 7:41:13 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendor generated by hbm2java
 */
public class Vendor implements java.io.Serializable {

	private BigDecimal vendorid;
	private String firstname;
	private String middlename;
	private String lastname;
	private String title;
	private String streetname;
	private String aptno;
	private String city;
	private String state;
	private String zip;
	private String country;
	private BigDecimal phonenumber;
	private BigDecimal mobilenumber;
	private String emailid;
	private String organization;
	private Set events = new HashSet(0);

	public Vendor() {
	}

	public Vendor(BigDecimal vendorid, String firstname, String lastname) {
		this.vendorid = vendorid;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	public Vendor(BigDecimal vendorid, String firstname, String middlename, String lastname, String title,
			String streetname, String aptno, String city, String state, String zip, String country,
			BigDecimal phonenumber, BigDecimal mobilenumber, String emailid, String organization, Set events) {
		this.vendorid = vendorid;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.title = title;
		this.streetname = streetname;
		this.aptno = aptno;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.phonenumber = phonenumber;
		this.mobilenumber = mobilenumber;
		this.emailid = emailid;
		this.organization = organization;
		this.events = events;
	}

	public BigDecimal getVendorid() {
		return this.vendorid;
	}

	public void setVendorid(BigDecimal vendorid) {
		this.vendorid = vendorid;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getStreetname() {
		return this.streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

	public String getAptno() {
		return this.aptno;
	}

	public void setAptno(String aptno) {
		this.aptno = aptno;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public BigDecimal getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(BigDecimal phonenumber) {
		this.phonenumber = phonenumber;
	}

	public BigDecimal getMobilenumber() {
		return this.mobilenumber;
	}

	public void setMobilenumber(BigDecimal mobilenumber) {
		this.mobilenumber = mobilenumber;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
